from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class AgentResult:
    """Standard envelope for agent responses."""

    agent: str
    content: str


@dataclass(frozen=True)
class PlanStep:
    """A structured step generated by the planner."""

    id: int
    title: str
    objective: str
    owner: str


class BaseAgent:
    """Base class for specialized agents."""

    name = "BaseAgent"

    def run(self, prompt: str) -> AgentResult:
        raise NotImplementedError


class PlannerAgent(BaseAgent):
    """Creates a concrete execution plan from a user objective."""

    name = "PlannerAgent"

    def create_plan(self, user_task: str) -> list[PlanStep]:
        return [
            PlanStep(
                id=1,
                title="Problem framing",
                objective=f"Clarify scope, constraints, and expected outcomes for: {user_task}",
                owner="Product Strategist",
            ),
            PlanStep(
                id=2,
                title="Audience and value mapping",
                objective="Identify target users, pain points, and core value propositions",
                owner="Market Researcher",
            ),
            PlanStep(
                id=3,
                title="Solution design",
                objective="Draft implementation strategy, architecture choices, and delivery phases",
                owner="Technical Lead",
            ),
            PlanStep(
                id=4,
                title="Launch and growth",
                objective="Define launch channels, activation loops, and retention levers",
                owner="Growth Lead",
            ),
            PlanStep(
                id=5,
                title="Measurement and risk",
                objective="Set measurable KPIs, identify risks, and define mitigations",
                owner="Operations Analyst",
            ),
        ]

    def run(self, prompt: str) -> AgentResult:
        plan = self.create_plan(prompt)
        lines = [f"{step.id}. {step.title} ({step.owner}) - {step.objective}" for step in plan]
        return AgentResult(agent=self.name, content="\n".join(lines))


class ResearchAgent(BaseAgent):
    """Expands each plan step into actionable guidance."""

    name = "ResearchAgent"

    def run(self, prompt: str) -> AgentResult:
        content = (
            f"Step analysis for '{prompt}':\n"
            "- Key decisions: define assumptions early and document trade-offs.\n"
            "- Dependencies: list required people, tools, and upstream artifacts.\n"
            "- Validation: identify one fast experiment and one success metric."
        )
        return AgentResult(agent=self.name, content=content)


class CriticAgent(BaseAgent):
    """Reviews output quality and surfaces execution risks."""

    name = "CriticAgent"

    def run(self, prompt: str) -> AgentResult:
        content = (
            "Quality and risk review:\n"
            "- Coverage: each major objective has an owner and measurable result.\n"
            "- Risks: timeline slippage, unclear ownership, and weak instrumentation.\n"
            "- Mitigations: short milestones, explicit RACI, and weekly KPI reviews.\n"
            "- Confidence: medium-high if execution cadence is maintained."
        )
        return AgentResult(agent=self.name, content=content)


class SynthesizerAgent(BaseAgent):
    """Combines all agent outputs into a concise final brief."""

    name = "SynthesizerAgent"

    def run(self, prompt: str) -> AgentResult:
        content = (
            "Executive brief:\n"
            f"{prompt}\n\n"
            "Recommended next action: start with a 2-week pilot, instrument the critical metrics, "
            "and iterate from evidence before scaling."
        )
        return AgentResult(agent=self.name, content=content)
